### Variables
@url = http://localhost:3000/api/v1
@type = grass

### Random pokemon
GET {{url}}/random-pokemon

### Specific pokemon
GET {{url}}/pokemon/5

### Random with type
GET {{url}}/random-pokemon/{{type}}

### Add new pokemon
POST {{url}}/add

{
    "id": 100,
    "name": "Ryan",
    "type": "Instructor"
}